pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Getting code from repository...'
                checkout scm
            }
        }

        stage('Compile') {
            steps {
                echo 'Compiling Java code...'
                sh 'javac src/*.java'
            }
        }

        stage('Run Program') {
            steps {
                echo 'Running the application...'
                sh 'java -cp src Main'
            }
        }
    }
}
